desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
is_serial_enabled: false
color_schemes:
  - - red
    - green
    - blue
  - - red
  - - green
  - - blue
  - - '#2a04ff'
    - '#ff9604'
  - - '#02e6ff'
    - '#ff4a02'
  - - '#2bff01'
    - '#ff0127'
  - - '#fff700'
    - '#f700ff'
  - - '#ee00ac'
    - blue
audio_ports:
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Built-in Microphone
    number_of_audio_samples: 24
    sampling_rate: 44000
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Loopback Audio
    number_of_audio_samples: 24
    sampling_rate: 44000
strips:
  - name: Flower
    serial_port_name: /dev/tty.usbserial-A50285BI
    active_state_index: 0
    is_online: false
    midi_ports_for_changing_mode:
      - Audio2Led ChangeMod TopBar
    midi_ports_for_visualization:
      - Audio2Led Synth
    original_physical_shape:
      - 80
      - 80
      - 80
      - 80
      - 80
    midi_range:
      - 47
      - 73
    scene:
      shapes:
        - offset:
            - 0
            - 0
          pixel_range:
            - 0
            - 80
          svg_string:
            M177.984757,139.00227 C173.670162,135.932865 250.142486,217.789438
            174.630054,286.403438 C104.97493,349.694465 36.9585081,270.036227 73.5285622,232.601427
        - offset:
            - 0
            - 0
          pixel_range:
            - 80
            - 160
          svg_string:
            M147.015243,136.398054 C142.762486,139.553189 244.244,92.1179459
            286.165838,185.138638 C324.834162,270.942573 228.056541,311.014195 203.75427,264.666032
        - offset:
            - 0
            - 0
          pixel_range:
            - 160
            - 240
          svg_string:
            M135.786054,165.123135 C137.471135,170.141838 123.7184,58.9686486
            225.140324,47.8448649 C318.693946,37.584 326.898703,142.007027 275.309081,150.797838
        - offset:
            - 0
            - 0
          pixel_range:
            - 240
            - 320
          svg_string:
            M158.855784,183.522422 C164.149946,183.47 54.1684,162.195676 74.9294703,62.2994595
            C94.0800865,-29.8459459 195.928973,-5.37924324 188.346811,46.4015135
        - offset:
            - 0
            - 0
          pixel_range:
            - 320
            - 400
          svg_string:
            M183.904324,169.945081 C185.491027,164.894054 131.271892,262.918551
            42.6808973,212.304141 C-39.0371027,165.616432 15.7041405,76.3127568 62.6075784,99.5258378
      size:
        width: 300
        height: 300
        scale: 1
    states:
      - name: Scroll
        active_visualizer_effect: scroll
        active_color_scheme_index: 0
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1.0
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 120
        chunk_size: 5
        blur_value: 1.8
        is_reverse: false
        is_mirror: false
      - name: Scroll-mirror-reverse
        active_visualizer_effect: scroll
        active_color_scheme_index: 0
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 0.4
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 1
        chunk_size: 5
        blur_value: 0.7
        is_reverse: true
        is_mirror: true
      - name: Spectrum
        active_visualizer_effect: spectrum
        active_color_scheme_index: 4
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 0.3
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 148
        chunk_size: 8
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: AltChunks
        active_visualizer_effect: alternate_color_chunks
        active_color_scheme_index: 0
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 151
        chunk_size: 20
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: MidiScrollShape
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 4
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 120
        chunk_size: 5
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: Fire
        active_visualizer_effect: fire
        active_color_scheme_index: 4
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 96
        chunk_size: 5
        blur_value: 4.0
        is_reverse: false
        is_mirror: false
