name: audio-2-led
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.16.4
  - pyaudio=0.2.11
  - colour=0.1.5
  - scipy=1.3.0
  - psutil=5.6.6
  - pyserial=3.4
  - setproctitle=1.1.10
  - pyyaml=5.2
  - zerorpc=0.6.3
  - pip=20.0.2
  - pip:
    - python-rtmidi
    - mido
    - blessed 
