desirated_framerate: 60
display_shell_interface: false
scene_camera:
  x: 0
  y: 2.3
  z: -7
is_zmq_api_enabled: true
is_serial_enabled: false
color_schemes:
- - red
  - green
  - blue
- - '#2a04ff'
  - '#ff9604'
- - '#02e6ff'
  - '#ff4a02'
- - '#2bff01'
  - '#ff0127'
- - '#fff700'
  - '#f700ff'
- - '#ee00ac'
  - blue
- - red
- - green
- - blue
- - yellow
- - pink
- - '#ee00ac'
  - blue
- - '#ee00ac'
  - black
- - '#ee00ac'
  - black
  - black
audio_ports:
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Built-in Microphone
  number_of_audio_samples: 24
  sampling_rate: 44000
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Loopback Audio
  number_of_audio_samples: 24
  sampling_rate: 44000
strips:
- name: Angles
  serial_port_name: /dev/tty.usbserial-A50285BI
  active_state_index: 9
  is_online: false
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod Center
  midi_ports_for_visualization:
  - Audio2Led Synth
  original_physical_shape:
  - 34
  - 52
  - 50
  midi_range:
  - 48
  - 72
  scene:
    backgrounds:
    - svg_string: M497.132,0 L777.225,0 L840.728,398.64 L431.864,398.64 L497.132,0
        Z
    - svg_string: M793.576,357.3241 L777.839,254.1 L690.856,358.2762 L793.576,357.3241
        Z
    - svg_string: M663.765,37.256 L674.975,227.94 L604.969,316.0282 L543.008,316.1892
        L648.753,197.563 L645.106,36.912 L663.765,37.256 Z
    - svg_string: M616.427,37.593 L618.238,181.825 L490.41,315.9248 L485.309,316.0775
        L498.115,233.379 L599.334,141.887 L600.82,37.417 L616.427,37.593 Z
    - svg_string: M745.68,37.595 L773.078,219.828 L689.322,315.9272 L651.016,315.9272
        L712.101,238.766 L695.745,37.595 L745.68,37.595 Z
    - svg_string: M527.326,36.495 L573.966,36.291 L570.285,122.849 L506.47,178.78
        L527.326,36.495 Z
    - svg_string: M343.596,0 L63.503,0 L0,398.64 L408.864,398.64 L343.596,0 Z
    - svg_string: M47.152,357.3241 L62.889,254.1 L149.872,358.2762 L47.152,357.3241
        Z
    - svg_string: M176.963,37.256 L165.753,227.94 L235.759,316.0282 L297.72,316.1892
        L191.975,197.563 L195.622,36.912 L176.963,37.256 Z
    - svg_string: M224.301,37.593 L222.49,181.825 L350.318,315.9248 L355.419,316.0775
        L342.613,233.379 L241.394,141.887 L239.908,37.417 L224.301,37.593 Z
    - svg_string: M95.048,37.595 L67.65,219.828 L151.406,315.9272 L189.712,315.9272
        L128.627,238.766 L144.983,37.595 L95.048,37.595 Z
    - svg_string: M313.402,36.495 L266.762,36.291 L270.443,122.849 L334.258,178.78
        L313.402,36.495 Z
    shapes:
    - pixel_range:
      - 86
      - 136
      svg_string: M161.912 37.534 147.873 233.115 212.654 317.0115
    - pixel_range:
      - 34
      - 86
      svg_string: M210.456 37.128 207.677 189.977 321.409 316.6306
    - pixel_range:
      - 0
      - 34
      svg_string: M253.13 36.927 254.919 130.693 338.855 203.987
    - pixel_range:
      - 86
      - 136
      svg_string: M678.816 37.534 692.855 233.115 628.074 317.0115
    - pixel_range:
      - 34
      - 86
      svg_string: M630.272 37.128 633.051 189.977 519.319 316.6306
    - pixel_range:
      - 0
      - 34
      svg_string: M587.598 36.927 585.809 130.693 501.873 203.987
  states:
  - name: sound-scroll
    active_visualizer_effect: scroll
    active_color_scheme_index: 5
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1.0
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 1
    chunk_size: 5
    blur_value: 1.1
    is_reverse: false
    is_mirror: false
  - name: sound-energy
    active_visualizer_effect: energy
    active_color_scheme_index: 0
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1.0
    audio_decay: 0.5
    division_value: 0
    max_brightness: 255
    time_interval: 1
    chunk_size: 18
    blur_value: 0.7
    is_reverse: false
    is_mirror: false
  - name: sound-flash
    active_visualizer_effect: channel_flash
    active_color_scheme_index: 11
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 120
    chunk_size: 5
    blur_value: 4.8
    is_reverse: true
    is_mirror: false
  - name: sound-itensity
    active_visualizer_effect: channel_intensity
    active_color_scheme_index: 11
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 120
    chunk_size: 5
    blur_value: 0.1
    is_reverse: true
    is_mirror: false
  - name: sound-spectrum
    active_visualizer_effect: spectrum
    active_color_scheme_index: 10
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 120
    chunk_size: 5
    blur_value: 0.1
    is_reverse: false
    is_mirror: false
  - name: midi-scroll
    active_visualizer_effect: piano_scroll
    active_color_scheme_index: 11
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 500
    chunk_size: 5
    blur_value: 0.8
    is_reverse: false
    is_mirror: false
  - name: midi-scroll-shape
    active_visualizer_effect: piano_echo
    active_color_scheme_index: 11
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 1
    chunk_size: 5
    blur_value: 0.1
    is_reverse: false
    is_mirror: false
  - name: midi-note
    active_visualizer_effect: piano_note
    active_color_scheme_index: 5
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 68
    chunk_size: 5
    blur_value: 0.8
    is_reverse: false
    is_mirror: false
  - name: time-alt-chunks
    active_visualizer_effect: alternate_color_chunks
    active_color_scheme_index: 13
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 203
    chunk_size: 12
    blur_value: 6.3
    is_reverse: false
    is_mirror: false
  - name: time-alt-shapes
    active_visualizer_effect: alternate_color_shapes
    active_color_scheme_index: 13
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 500
    chunk_size: 5
    blur_value: 0.1
    is_reverse: false
    is_mirror: false
  - name: time-fade-colors
    active_visualizer_effect: transition_color_shapes
    active_color_scheme_index: 5
    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 120
    chunk_size: 5
    blur_value: 0.1
    is_reverse: false
    is_mirror: false
  - name: generic-fire
    active_visualizer_effect: fire
    active_color_scheme_index: 4
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 1
    audio_decay: 0.2
    division_value: 0
    max_brightness: 255
    time_interval: 282
    chunk_size: 5
    blur_value: 2.7
    is_reverse: true
    is_mirror: false
